# Generated by Django 3.2.5 on 2021-07-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.FloatField(null=True),
        ),
    ]
