# Generated by Django 3.2.5 on 2021-07-16 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_currentbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='imageSrc',
            new_name='imageURL',
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sellerListings', to=settings.AUTH_USER_MODEL),
        ),
    ]
